# Generated by Django 5.1.6 on 2025-03-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_assignment_created_at_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default='chemistry', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
    ]
