# Generated by Django 5.1.6 on 2025-03-05 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
