# Generated by Django 5.1.6 on 2025-03-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_assignment_updated_at_alter_submission_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/img/assignments/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/subjects/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/submissions/'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
