# Generated by Django 5.1.6 on 2025-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_submission_question_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
