# Generated by Django 5.1.6 on 2025-03-07 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_assignment_file_alter_subject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Attempted', 'Attempted'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
