# Generated by Django 6.0.3 on 2026-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_blogpost_sitesettings_systemupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
